config/routes.rb
Rails.application.routes.draw do
root "tops#index"

 resources :users
 get "/signup", to: "users#new"
 post "/signup", to: "users#create"

 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"

 resources :children, except: [:index] do
   delete :purge, on: :member
 end

 resources :growths do
   get :detail, on: :member
 end

 resources :microposts do
   delete :purge, on: :member
 end

 resources :maps

 resources :families do
   post :share, on: :member
 end

 get "/edit", to: "static_pages#edit"

end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def edit; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/edit.html.erb
<div class="container" id="main_background">  <%# ページ全体を囲むコンテナ%>
<br>
<h2 class="text-center">各種設定</h2>

<div class="col-md-offset-4 col-md-4 well"> <%# グリッドシステム%>
  <div id="static_edit_menu">
    <%= link_to 'ユーザーの設定変更', edit_user_path(session[:user_id]), class:"button text-center", id:"static_edit_list" %>
    <%= link_to '子どもの設定変更', edit_child_path(session[:child_id]), class:"button text-center", id:"static_edit_list" %>
    <%= link_to '別のユーザーと連携', families_path, class:"button text-center", id:"static_edit_list" %>
    <%= link_to '子どもの一覧', user_path(session[:user_id]), class:"button text-center", id:"static_edit_list" %>
    <%= link_to "新しい子どもを登録", new_child_path, class:"button text-center", id:"static_edit_list" %>
    <%= link_to "ログアウト", logout_path, method: :delete, class:"button text-center", id:"static_edit_list" %>
    <%= link_to child_path(session[:child_id]) do %>
      <%= fa_icon("backward") %> トップページに戻る
    <% end %>
  </div>

</div> <%# グリッドシステム%>
</div> <%# ページ全体を囲むコンテナ%>