config/routes.rb
Rails.application.routes.draw do
root "tops#index"

 resources :users
 get "/signup", to: "users#new"
 post "/signup", to: "users#create"

 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"

 resources :children, except: [:index] do
   delete :purge, on: :member
 end

 resources :growths do
   get :detail, on: :member
 end

 resources :microposts do
   delete :purge, on: :member
 end

 resources :maps

 resources :families do
   post :share, on: :member
 end

 get "/edit", to: "static_pages#edit"

end

app/models/growth.rb
# frozen_string_literal: true

class Growth < ApplicationRecord
  belongs_to :user
  belongs_to :child

  validates :user_id, presence: true
  validates :child_id, presence: true
  validates :weight, presence: true
  validates :height, presence: true

  scope :search, lambda { |search_params|
    return if search_params.blank?

    date_from(search_params[:date_from]).date_to(search_params[:date_to])
  }
  scope :date_from, ->(from) { where('? <= date', from) if from.present? }
  scope :date_to, ->(to) { where('date <= ?', to) if to.present? }
end

app/controllers/growths_controller.rb
# frozen_string_literal: true

class GrowthsController < ApplicationController
  before_action :logged_in_user, except: %i[index detail]
  before_action :making_user, only: :destroy

  def index
    @child = Child.find(session[:child_id])
    gon.growth = @child.growths.count
    gon.date = @child.growths.pluck(:date)
    gon.height = @child.growths.pluck(:height)
    gon.weight = @child.growths.pluck(:weight)
  end

  def new
    @child = Child.find(session[:child_id])
    @growth = Growth.new
  end

  def create
    @child = Child.find(session[:child_id])
    @growth = @child.growths.build(growth_params)
    if @growth.save
      flash[:success] = '登録が完了しました！'
      redirect_to growths_url
    else
      render 'new'
    end
  end

  def detail
    @child = Child.find(session[:child_id])
    @search_params = growth_search_params
    @growths = @child.growths.search(@search_params)
                     .paginate(page: params[:page], per_page: 5)
  end

  def edit
    @child = Child.find(session[:child_id])
    @growth = Growth.find(params[:id])
  end

  def update
    @child = Child.find(session[:child_id])
    @growth = Growth.find(params[:id])
    if @growth.update_attributes(growth_params)
      flash[:success] = '更新が完了しました！'
      redirect_to growths_url
    else
      render 'edit'
    end
  end

  def destroy
    Growth.find(params[:id]).destroy
    flash[:success] = '削除しました。'
    redirect_to growths_url
  end

  private

  def growth_search_params
    params.fetch(:search, {}).permit(:date_from, :date_to, :name)
  end

  def growth_params
    params.require(:growth).permit(:date, :height, :weight, :child_id, :user_id)
  end

  def making_user
    @current_user_id = session[:user_id]
    growth = Growth.find(params[:id])
    @making_user_id = growth.user_id
    redirect_to detail_growth_url if @current_user_id != @making_user_id
  end
end

app/helpers/growths_helper.rb
# frozen_string_literal: true

module GrowthsHelper
end

app/views/growths/detail.html.erb
<div class="container">  <%# ページ全体を囲むコンテナ%>
  <h2 class="text-center">身長・体重の修正</h2><br>

<div class="col-md-offset-2 col-md-8 well"> <%# グリッドシステム%>
  <div class="search-form">
    <%= form_with(scope: :search, url: detail_growth_path, method: :get, local: true, :html => {:class => "form-inline"} ) do |form| %>
      <%= form.label:測定日 %>
      <div class="form-group">
        <div class='input-group date datepicker'>
          <%= form.date_field :date_from, value: @search_params[:date_from], class:"form-control" %>
        </div>
      </div>
      ~
      <div class="form-group">
        <div class='input-group date' id='datetimepicker'>
          <%= form.date_field :date_to, value: @search_params[:date_to], class:"form-control" %>
        </div>
      </div>
      <%= form.submit "検索", class:"button" %>
    <% end %>
  </div><br>

  <table class="table">
     <thead>
       <tr>
         <th>測定した日</th>
         <th>身長(cm)</th>
         <th>体重(kg)</th>
         <th>投稿者</th>
         <th>修正</th>
         <th>削除</th>
       </tr>
     </thead>
     <tbody>
       <% @growths.reverse_each do |form| %>
        <tr>
        <td><%= form.date.strftime("%Y年%m月%d日")  %></td>
        <td><%= form.weight %></td>
        <td><%= form.height %></td>
        <td><%= User.find(form.user_id).name %></td>
        <% if form.user_id == session[:user_id] %>
          <td><%= link_to '修正', edit_growth_path(form) %></td>
          <td><%= link_to '削除', growth_path(form), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        <% end %>
       </tr>
       <% end %>
     </tbody>
  </table>

  <%= will_paginate @growths, :renderer => BootstrapPagination::Rails %><br>

  <%= link_to growths_path do %>
    <%= fa_icon("backward") %> 前のページに戻る
  <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

app/views/growths/edit.html.erb
<div class="container">  <%# ページ全体を囲むコンテナ%>
  <br>
  <h2 class="text-center">身長・体重の修正</h2><br>

  <div class="col-md-offset-3 col-md-6 well"> <%# グリッドシステム%>
  <%= form_for(@growth) do |form| %>
  <%= render "shared/error_messages", object: form.object %>
　  <div class="form-group">
    <%= form.label :測定日 %>
    <div class='input-group date datepicker'>
      <%= form.date_field :date, class:"form-control" %>
　  </div>
    </div>

    <div class="form-group">
      <%= form.label :身長 %>
      <%= form.number_field :height, :step=>"0.1", class:"form-control" %>
　  </div>

    <div class="form-group">
      <%= form.label :体重 %>
      <%= form.number_field :weight, :step=>"0.1", class:"form-control" %>
　  </div>

      <%= form.hidden_field :user_id, value:session[:user_id] %>

    <div class="form-group">
      <%= form.submit "データを修正", class:"button" %>
    </div>
  <% end %>
  <br>

  <%= link_to growths_path do %>
    <%= fa_icon("backward") %> 「身長・体重」の一覧ページに戻る
  <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

app/views/growths/index.html.erb
<div class="container"> <%# ページ全体を囲むコンテナ%>
<br>
<h2 class="text-center">身長・体重</h2>
<br>

<div class="col-md-offset-1 col-md-10 well"> <%# グリッドシステム%>

  <div style="height:60vh">
    <canvas id="myChart"></canvas>
    <script>draw_graph();</script>
  </div>
  <br>

<div class="growth_select">
  <%= link_to new_growth_path, class:"button", id:"growth_button"  do %>
    <%= fa_icon("pencil-square-o") %> 記録の入力
  <% end %>
  <%= link_to detail_growth_path(session[:child_id]), class:"button", id:"growth_button" do %>
    <%= fa_icon("file") %> 記録の修正
  <% end %>
</div>

<%= link_to child_path(session[:child_id]) do %>
  <%= fa_icon("backward") %> トップページに戻る
<% end %>

</div> <%# グリッドシステム%>
</div> <%# ページ全体を囲むコンテナ%>

app/views/growths/new.html.erb
<div class="container">  <%# ページ全体を囲むコンテナ%>
<br>
<h2 class="text-center">身長・体重の入力</h2>
<br>
<div class="col-md-offset-3 col-md-6 well"> <%# グリッドシステム%>
  <%= form_for(@growth, url:growths_path) do |form| %>
  <%= render "shared/error_messages", object: form.object %>
    <div class="form-group">
      <%= form.label :測定日 %>
              <div class='input-group date datepicker'>
      <%= form.date_field :date, class:"form-control", value:Date.today %>
    </div>
  </div>

    <div class="form-group">
      <%= form.label :身長 %>
      <%= form.number_field :height, :step=>"0.1", class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :体重 %>
      <%= form.number_field :weight, :step=>"0.1", class:"form-control" %>
    </div>

      <%= form.hidden_field :user_id, value:session[:user_id] %>

    <div class="form-group">
      <%= form.submit "データを入力", class:"button" %>
    </div>
  <% end %>
<br>

  <%= link_to growths_path do %>
    <%= fa_icon("backward") %> 前のページに戻る
  <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

app/views/growths/show.html.erb
<h1>Growths#show</h1>
<p>Find me in app/views/growths/show.html.erb</p>