config/routes.rb
Rails.application.routes.draw do
root "tops#index"

 resources :users
 get "/signup", to: "users#new"
 post "/signup", to: "users#create"

 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"

 resources :children, except: [:index] do
   delete :purge, on: :member
 end

 resources :growths do
   get :detail, on: :member
 end

 resources :microposts do
   delete :purge, on: :member
 end

 resources :maps

 resources :families do
   post :share, on: :member
 end

 get "/edit", to: "static_pages#edit"

end

app/models/family.rb
# frozen_string_literal: true

class Family < ApplicationRecord
  belongs_to :child
  belongs_to :user

  validates :child_id, presence: true
  validates :user_id, presence: true
end

app/controllers/families_controller.rb
# frozen_string_literal: true

class FamiliesController < ApplicationController
  before_action :parent_user, only: :show
  before_action :address_blank_check, only: :share

  def index
    @user = User.find(session[:user_id])
    @children = @user.children
  end

  def new
    render layout: 'headerless_layout'
  end

  def create
    @user = User.find(family_params[:user_id])
    if Child.where(name: family_params[:child_name])
            .where(id: family_params[:child_id]).presence
      @child = Child.find(family_params[:child_id])
      if @child.child_password == family_params[:child_password]
        @user.children << @child
        flash[:success] = '別の保護者の方から子どもを共有しました！'
        redirect_to @child
      else
        flash[:danger] = '子どもの名前もしくはIDに誤りがあります！'
        render 'new', layout: 'headerless_layout'
      end
    else
      flash[:danger] = 'パスワードに誤りがあります！'
      render 'new', layout: 'headerless_layout'
    end
  end

  def show
    @child = Child.find(params[:id])
  end

  def share
    UserMailer.share_child(session[:user_id],
                           params[:id],
                           params[:address]).deliver_now
    flash[:success] = 'メールを送信しました'
    redirect_to families_url
  end

  private

  def family_params
    params.require(:family).permit(:child_id,
                                   :child_name,
                                   :child_password,
                                   :user_id,
                                   :address)
  end

  def parent_user
    @current_user_id = session[:user_id]
    @child_id = Child.find(params[:id])
    return if Family.where(user_id: @current_user_id)
                    .where(child_id: @child_id).presence

    redirect_to login_url
  end

  def address_blank_check
    return if params[:address].presence

    flash.now[:danger] = 'アドレスが空欄になっています！'
    @child = Child.find(params[:id])
    render 'show'
  end
end

app/controllers/familys_controller.rb
# frozen_string_literal: true

class FamilysController < ApplicationController
  before_action :parent_user, only: :show
  before_action :address_blank_check, only: :share

  def index
    @user = User.find(session[:user_id])
    @children = @user.children
  end

  def new
    render layout: 'headerless_layout'
  end

  def create
    @user = User.find(family_params[:user_id])
    if Child.where(name: family_params[:child_name])
            .where(id: family_params[:child_id]).presence
      @child = Child.find(family_params[:child_id])
      if @child.child_password == family_params[:child_password]
        @user.children << @child
        flash[:success] = '別の保護者の方から子どもを共有しました！'
        redirect_to @child
      else
        flash[:danger] = '子どもの名前もしくはIDに誤りがあります！'
        render 'new', layout: 'headerless_layout'
      end
    else
      flash[:danger] = 'パスワードに誤りがあります！'
      render 'new', layout: 'headerless_layout'
    end
  end

  def show
    @child = Child.find(params[:id])
  end

  def share
    UserMailer.share_child(session[:user_id],
                           params[:id],
                           params[:address]).deliver_now
    flash[:success] = 'メールを送信しました'
    redirect_to familys_url
  end

  private

  def family_params
    params.require(:family).permit(:child_id,
                                   :child_name,
                                   :child_password,
                                   :user_id,
                                   :address)
  end

  def parent_user
    @current_user_id = session[:user_id]
    @child_id = Child.find(params[:id])
    return if Family.where(user_id: @current_user_id)
                    .where(child_id: @child_id).presence

    redirect_to login_url
  end

  def address_blank_check
    return if params[:address].presence

    flash.now[:danger] = 'アドレスが空欄になっています！'
    @child = Child.find(params[:id])
    render 'show'
  end
end

app/helpers/familys_helper.rb
# frozen_string_literal: true

module FamilysHelper
end

app/views/families/index.html.erb
<div class="container" id="main_background">  <%# ページ全体を囲むコンテナ%>
<br><br>

  <h2 class="text-center">別のユーザーと連携</h2>
  <p class="text-center">別の保護者(ユーザー)と子どもを共有することができます。</p><br>

  <div class="col-md-offset-4 col-md-4 well"> <%# グリッドシステム%>

  <h3>子どものデータを送る</h3>
    <table class="table">
      <tbody>
        <% @children.each do |form| %>
          <tr>
            <td><%= form.name %></td>
            <td><%= link_to 'メール送付画面へ',family_path(form) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <h3>子どものデータを受け取る</h3>

      <%= link_to '入力画面へ', new_family_path, class:"button" %><br><br><br>

  <%= link_to edit_path do %>
    <%= fa_icon("backward") %> 前のページに戻る
  <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

app/views/families/new.html.erb
<% if session[:user_id].presence && session[:child_id].presence %>
  <%= render "layouts/header" %>
<% end %>

<div class="container">  <%# ページ全体を囲むコンテナ%>
<br>

  <h2 class="text-center">子どものデータを受け取る</h2>
  <p class="text-center">別のユーザーから送られたデータを入力すると、子どもを共有することができます。</p><br>

<div class="col-md-offset-4 col-md-4 well"> <%# グリッドシステム%>
  <%= form_with scope: :family, url:families_path, local:true do |form| %>
    <div class="form-group">
      <%= form.label :子どものID %>
      <%= form.number_field :child_id, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :子どもの名前 %>
      <%= form.text_field :child_name, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :パスワード%>
      <%= form.text_field :child_password, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.hidden_field :user_id, class:"form-control", value:session[:user_id] %>
    </div>

    <%= button_tag :type => "submit", :class =>"button" do %>
      <%= fa_icon("child") %> データを受け取る
    <% end %>
  <% end %>
　<br><br>

<%= link_to families_path do %>
  <%= fa_icon("backward") %> 前のページに戻る
<% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

app/views/families/show.html.erb
<div class="container" id="main_background">  <%# ページ全体を囲むコンテナ%>
<br><br>

<h2 class="text-center">
  <% if @child.sex == "男の子" %>
  <p><%= @child.name %>くんのパスワード</p>
  <% else %>
  <p><%= @child.name %>ちゃんのパスワード</p>
  <% end %>
</h2>
<p class="text-center">「パスワード情報」の内容を「送信先」のアドレスに送ります。</p>
<br>

<div class="col-md-offset-3 col-md-6 well"> <%# グリッドシステム%>

    <h4>パスワード情報</h4>
    <table class="table">
      <tbody>
        <tr><td><span>Ｉ　　　Ｄ</span></td>
　          <td><span><%= @child.id %></span></td></tr>
        <tr><td><span>名　　　前</span></td>
　          <td><span><%= @child.name %></span></td></tr>
        <tr><td><span>パスワード</span></td>
            <td><span><%= @child.child_password %></span></td></tr>
      </tbody>
    </table>

    <h4>送信先</h4>
      <%= form_with url:share_family_path, method: :post, local:true do |form| %>
        <div class="form-group">
          <%= form.text_field :address, placeholder:"共有したい相手のアドレスを入力してください。", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= button_tag :type => "submit", :class =>"button", data: { confirm: "メールを送信します。入力したアドレスに誤りはないですか？"} do %>
            <%= fa_icon("envelope") %> 送　信
          <% end %>
        </div>
      <% end %>

    <br>
    <%= link_to edit_path do %>
      <%= fa_icon("backward") %> 前のページに戻る
    <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>