config/routes.rb
Rails.application.routes.draw do
root "tops#index"

 resources :users
 get "/signup", to: "users#new"
 post "/signup", to: "users#create"

 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"

 resources :children, except: [:index] do
   delete :purge, on: :member
 end

 resources :growths do
   get :detail, on: :member
 end

 resources :microposts do
   delete :purge, on: :member
 end

 resources :maps

 resources :families do
   post :share, on: :member
 end

 get "/edit", to: "static_pages#edit"

end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < Album
  belongs_to :user
  belongs_to :child
  has_many_attached :images

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :child_id, presence: true
  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :logged_in_user, except: %i[index show]
  before_action :making_user, only: :destroy

  def index
    @child = Child.find(session[:child_id])
    @microposts = @child.microposts.paginate(page: params[:page], per_page: 5)
  end

  def new
    @child = Child.find(session[:child_id])
    @micropost = @child.microposts.build
    @map = @child.maps.build
    render layout: 'creating_new_map'
  end

  def create
    @child = Child.find(session[:child_id])
    @micropost = @child.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = '記事の登録が完了しました！'
      redirect_to microposts_url
    else
      render 'new'
    end
  end

  def edit
    @child = Child.find(session[:child_id])
    @micropost = Micropost.find(params[:id])
  end

  def update
    @child = Child.find(session[:child_id])
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = '記事の編集が完了しました！'
      redirect_to microposts_url
    else
      render 'edit'
    end
  end

  def destroy
    Micropost.find(params[:id]).destroy
    flash[:success] = '記事を削除しました！'
    redirect_to microposts_url
  end

  def purge
    Micropost.find(params[:id]).images.purge
    flash[:success] = '画像を削除しました'
    redirect_to edit_micropost_url(params[:id])
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :user_id, images: [])
  end

  def making_user
    @current_user_id = session[:user_id]
    micropost = Micropost.find(params[:id])
    @making_user_id = micropost.user_id
    redirect_to microposts_url if @current_user_id != @making_user_id
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <%= link_to "delete", micropost, method: :delete,
                                         data: { confirm: "You sure?" } %>
  </span>
</li>

app/views/microposts/edit.html.erb
<div class="container" id="main_background">  <%# ページ全体を囲むコンテナ%>
<br>
<h2 class="text-center">記事の編集</h2>
<br>

<div class="col-md-offset-3 col-md-6 well"> <%# グリッドシステム%>

  <%= form_for(@micropost) do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <div class="form-group", id:"input_field">
    <%= form.label :今日の出来事 %><br>
    <%= form.text_area :content, class:"form-control", size:"20x10", id: "input-text" %>
    <p id="counter">残り300文字</p>
  </div>

  <div class="field image">
    <%= form.label '写真' %>
    <div id="img_field" onClick="$('#file').click()" >
      <% if @micropost.images.attached? %>
        <% @micropost.images.each do |image| %>
          <%= image_tag image.variant(resize: "300x300") %>
        <% end %>
      <% else %>
        <div class="text-center"><%= fa_icon("file-image-o") %></div>
      <% end %>
    </div>
    <% if @micropost.images.attached? %>
      <%= link_to '削除する', purge_micropost_path(@micropost), method: :delete, data: { confirm: '本当に削除しますか?' } %>
    <% end %>
    <%= form.file_field :images, multiple: true, style: "display:none;", id: "file"%>
  </div>
  <br>

  <%= button_tag :type => "submit", :class =>"button" do %>
    <%= fa_icon("pencil-square-o") %> 修正する
  <% end %>

  <% end %>
  <br>

  <%= link_to microposts_path do %>
    <%= fa_icon("backward") %> アルバム一覧に戻る
  <% end %>

</div> <%# グリッドシステム%>
</div>  <%# ページ全体を囲むコンテナ%>

<script>
  $(document).ready(function(){
    $fileField = $('#file')

    $($fileField).on('change', $fileField, function(e) {
      file = e.target.files[0]
      reader = new FileReader(),
      $preview = $("#img_field");

      reader.onload = (function(file) {
        return function(e) {
          $preview.empty();
          $preview.append($('<img>').attr({
            src: e.target.result,
            width: "100%",
            height: "100%",
            class: "preview",
            title: file.name
          }));
        };
      })(file);
      reader.readAsDataURL(file);
    });
  });
</script>

app/views/microposts/index.html.erb
<div class="container">  <%# ページ全体を囲むコンテナ%>
<div class="col-md-offset-3 col-md-6"> <%# グリッドシステム%>

  <h2 class="text-center" id="page_title">アルバム</h2>
  <p class="text-center">子どもの成長を写真とともに記録できます。</p>

  <%= link_to new_micropost_path, class:"button" do %>
    <%= fa_icon("pencil-square-o") %> 記事を追加
  <% end %>
  <br>

  <% @microposts.each do |form| %>
  　<div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><%= form.created_at.strftime("%Y年%m月%d日") %>(投稿者：<%= User.find(form.user_id).name %>)</h4>
      </div>

      <div class="panel-body">
        <p id="font_size"><%= form.content %></p>
        <% if form.images.attached? %>
          <% form.images.each do |image| %>
            <%= image_tag image.variant(resize:'300x300') %>
          <% end %>
        <% end %>
      </div>

      <div class="panel-footer">
        <% if form.user_id == session[:user_id] %>
          <%= link_to '修正する', edit_micropost_path(form) %>
          <%= link_to '削除する', micropost_path(form), method: :delete, data: { confirm: '本当に削除しますか?' } %>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= will_paginate @microposts, :renderer => BootstrapPagination::Rails %>　
  <br>

  <%= link_to child_path(session[:child_id]) do %>
    <%= fa_icon("backward") %> トップページに戻る
  <% end %>
  <br><br>

</div> <%# グリッドシステム%>
</div> <%# ページ全体を囲むコンテナ%>

app/views/microposts/new.html.erb
<div class="container">  <%# ページ全体を囲むコンテナ%>
<br>
<h2 class="text-center">アルバムを作成する</h2>
<br>
<div class="col-md-offset-3 col-md-6 well">

    <%= form_for(@micropost) do |form| %>
    <%= render "shared/error_messages", object: form.object %>
    <div class="form-group">
      <%= form.label :今日の出来事 %><br>
      <%= form.text_area :content, class:"form-control", size:"20x10", id: "input-text" %>
      <p id="counter">残り300文字</p>
    </div><br>

    <div class="field image">
      <%= form.label '写真' %>
      <div id="img_field" onClick="$('#file').click()" >
        <% if @micropost.images.attached? %>
          <% @micropost.images.each do |image| %>
            <%= image_tag image.variant(resize: "300x300") %>
          <% end %>
        <% else %>
          <div class="text-center"><%= fa_icon("file-image-o") %></div>
        <% end %>
      </div>
      <%= form.file_field :images, multiple: true, style: "display:none;", id: "file"%>
    </div>

    <%= form.hidden_field :user_id, value:session[:user_id] %><br>

    <%= button_tag :type => "submit", :class =>"button" do %>
      <%= fa_icon("pencil-square-o") %> アルバムを追加
    <% end %>
    <% end %><br>

    <%= link_to microposts_path do %>
      <%= fa_icon("backward") %> アルバム一覧に戻る
    <% end %>
  <br>
</div>
</div> <%# ページ全体を囲むコンテナ%>

<script>
  $(document).ready(function(){
    $fileField = $('#file')

    $($fileField).on('change', $fileField, function(e) {
      file = e.target.files[0]
      reader = new FileReader(),
      $preview = $("#img_field");

      reader.onload = (function(file) {
        return function(e) {
          $preview.empty();
          $preview.append($('<img>').attr({
            src: e.target.result,
            width: "100%",
            height: "100%",
            class: "preview",
            title: file.name
          }));
        };
      })(file);
      reader.readAsDataURL(file);
    });
  });
</script>